
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione5;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int CHAR_CONST = 51;
  public static final int POW = 36;
  public static final int CHAR = 20;
  public static final int GE = 43;
  public static final int INTEGER_CONST = 49;
  public static final int SEMI = 12;
  public static final int INT = 16;
  public static final int OUT = 3;
  public static final int RBRAC = 28;
  public static final int FOR = 4;
  public static final int MINUS = 33;
  public static final int WRITE = 23;
  public static final int NOT = 46;
  public static final int AND = 44;
  public static final int LT = 40;
  public static final int RPAR = 26;
  public static final int OR = 45;
  public static final int BOOL = 19;
  public static final int COMMA = 13;
  public static final int DIV = 35;
  public static final int FLOAT_CONST = 50;
  public static final int LOOP = 10;
  public static final int PLUS = 32;
  public static final int ASSIGN = 30;
  public static final int MAIN = 11;
  public static final int IF = 5;
  public static final int WRITELN = 24;
  public static final int ID = 47;
  public static final int LE = 41;
  public static final int EOF = 0;
  public static final int RETURN = 31;
  public static final int TRUE = 52;
  public static final int error = 1;
  public static final int PIPE = 14;
  public static final int VOID = 21;
  public static final int EQ = 38;
  public static final int TIMES = 34;
  public static final int COLON = 29;
  public static final int ELSE = 6;
  public static final int READ = 22;
  public static final int TO = 9;
  public static final int WHILE = 8;
  public static final int STR_CONCAT = 37;
  public static final int FLOAT = 17;
  public static final int THEN = 7;
  public static final int NE = 39;
  public static final int LPAR = 25;
  public static final int STRING = 18;
  public static final int DEF = 2;
  public static final int LBRAC = 27;
  public static final int FALSE = 53;
  public static final int STRING_CONST = 48;
  public static final int GT = 42;
  public static final int VAR = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "OUT",
  "FOR",
  "IF",
  "ELSE",
  "THEN",
  "WHILE",
  "TO",
  "LOOP",
  "MAIN",
  "SEMI",
  "COMMA",
  "PIPE",
  "VAR",
  "INT",
  "FLOAT",
  "STRING",
  "BOOL",
  "CHAR",
  "VOID",
  "READ",
  "WRITE",
  "WRITELN",
  "LPAR",
  "RPAR",
  "LBRAC",
  "RBRAC",
  "COLON",
  "ASSIGN",
  "RETURN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "STR_CONCAT",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "ID",
  "STRING_CONST",
  "INTEGER_CONST",
  "FLOAT_CONST",
  "CHAR_CONST",
  "TRUE",
  "FALSE"
  };
}

